# Style guide for StatPREP Lessons

One of the techniques for making lessons accessible to students is to have a consistent *style* across documents. Students don't know at first which variations in the way a lesson is written are important and worth taking note of, and which reflect casual and unimportant decisions made by the lesson's author. Adopting a consistent style reduces the student's cognitive load.

There are several aspects to style covered by this document:

1. When to use command exercise blocks.
1. The layout of tabular displays of data, that is, how do data tables get displayed.
2. The commands available to the user of the lesson, that is, what R packages are available to any user of the lesson.
3. The dialect of R used in commands.

We'll revise this guide based on experience and the availability of new facilities in R. 

## 1. When to use command exercise blocks

Use these freely, even when all that is required of a student is to press "Run code." This increases engagement by the student and helps to reinforce the close connection between running commands and doing statistics. 


Particular indications that you should use a command block rather than displaying a command and its result ...

1. You want the student to see the command.
2. A graphic or other complex output is displayed. (It's nice when students can cook their own eye candy.)



## 2. Layout of tabular displays

Unless there is some pressing reason to do otherwise:

1. The raw display of data tables in a narrative section should have the same style as data displayed as the result of running a command block.
2. For data sets that are small (say, < 100KB), display the whole data frame in a paged display, rather than using `head()`.  
3. Set the default knitr table printing method to DT (?????) so that the printing command does not need to be part of a command displayed to students. 

## 3. Commands available to the student

Even if a lesson is not using the command dialect specified in Section YYYY, the lesson should make readily available to the student the tidyverse as well as mosaic, and ggformula. So include these in the lesson's setup chunk. 

## 4. Command dialects


1. Use `read_csv()` and the like to store data as tibbles.
2. Data wrangling should be done using the tidyverse, especially `dplyr` and `tidyr`.

    a. Prefer `filter()` and `select()` over `subset()`.
    b. Avoid indexing by brackets or `$`.
    c. Prefer using pipes for short wrangling statements. Each step in the pipe should go on its own line.
3. Use formula-based statistics and graphics whenever possible (which, for intro stats, is "always"). 

If there's a compelling reason to put these guidelines to the side, for instance, you're writing a lesson about `ggplot()` or `data.table`, don't obsess about using the preferred command dialects.

4. Be tidy. If the result of a calculation can sensibly be stored as a dataframe/tibble, do so. For instance, avoid commands that generate isolated vectors. Instead, create a dataframe/tibble with a single column.



